server:
  host: "localhost"
  port: 8080

database:
  username: "root"
  password: "Ky@r4fzj"
  host: "127.0.0.1"
  port: 3306
  dbname: "stack"

crawl:
  debug: "true"
  period:
    - "2024"
  code:
    - "603205"

